language: python

dist: trusty

# See: https://docs.travis-ci.com/user/languages/python/
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

matrix:
  include:
    - {python: "2.6",      env: SKIP_GEVENT=true}
    - {python: "2.7",      env: SKIP_GEVENT=true}
    - {python: "3.7-dev",  env: SKIP_GEVENT=true}
    - {python: "nightly",  env: SKIP_GEVENT=true}

install:
    - python setup.py install
    - "[[ -n $SKIP_GEVENT ]] || pip install gevent"
    - "pip install paramiko || true"

before_script:
    - "echo NoHostAuthenticationForLocalhost yes >> ~/.ssh/config"
    - "echo StrictHostKeyChecking no >> ~/.ssh/config"
    - "ssh-keygen -q -f ~/.ssh/id_rsa -N ''"
    - "cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys"
    - "uname -a"
    - "hostname"
    - "cd tests"

script:
    - nosetests -vv -I test_deploy -I test_gevent_server
    # need to run in its own python interpreter (`monkey.patch_all()`):
    - "[[ -n $SKIP_GEVENT ]] || python test_gevent_server.py"
    # it currently fails on all but the native python versions on travis:
    - python test_deploy.py || true

notifications:
    email:
        on_success: change
        on_failure: change
