language: python

dist: trusty

# See: https://docs.travis-ci.com/user/languages/python/
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"
    - "nightly"

install:
    - pip install -e git+git://github.com/tomerfiliba/plumbum.git#egg=plumbum

before_script:
    - "pip install paramiko || true"
    - "echo NoHostAuthenticationForLocalhost yes >> ~/.ssh/config"
    - "echo StrictHostKeyChecking no >> ~/.ssh/config"
    - "ssh-keygen -q -f ~/.ssh/id_rsa -N ''"
    - "cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys"
    - "uname -a"
    - "hostname"
    - "python setup.py install"
    - "cd tests"

script:
    - nosetests -vv -I test_deploy
    # it currently fails on all but the native python versions on travis:
    - python test_deploy.py || true

notifications:
    email:
        on_success: change
        on_failure: change
